name: Run tests

on:
  pull_request:
    branches:
      - main
      - stage
  push:
    branches:
      - main
      - stage

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: {python-version: "3.12"}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Run tests & create coverage.xml
        run: |
          uv run pytest -v \
            --cov=. \
            --cov-config=.coveragerc \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=60 \
            --junitxml=junit.xml -o junit_family=legacy
        env:
          BOT_TOKEN: "some_token"
          CHAT_IDS: 111
          REDIS_HOST: "host"
          REDIS_PORT: 111
          TOPN_DB_BASE_URL: "http://host:111"
